# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MeuTimeFcApp' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeuTimeFcApp

  

  platform :ios, '9.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'MeuTimeFcAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MeuTimeFcApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeuTimeFcApp-tvOS

  target 'MeuTimeFcApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
